name: gha test
on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Clang-format
        run: sudo apt update && sudo apt install -y clang-format

      - name: Run clang-format for changed files
        run: |
          git clang-format --diff main | tee clang-format-diff.txt
          if [ -s clang-format-diff.txt ]; then
            echo "clang-format issues found in the following files:"
            cat clang-format-diff.txt
            exit 1
          else
            echo "No clang-format issues found."
          fi
