name: gha test
on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Clang-format
        run: sudo apt update && sudo apt install -y clang-format

      - name: Run clang-format for changed files
        id: clang-format
        run: |
          git clang-format --style LLVM --extensions cpp --diff ${{ github.event.pull_request.base.sha }} > clang-format-diff.txt
          echo "result=$?" >> "$GITHUB_OUTPUT"

      - name: Check clang-format result
        if: steps.clang-format.outputs.result != '0'
        run: |
          echo "::error::Clang-format check failed. Please format your code."
